core/blog/urls.py
from django.urls import path
from .views import blog_list , blog_detil
app_name = 'blog'
urlpatterns = [
    path('',blog_list,name='blog'),
    path('\<int:id>',blog_detil,name='detail'),
]

core/consulat/urls.py
from django.urls import path
from .views import consulatlist , consulatdetail , add_counslating
app_name = 'consulat'
urlpatterns = [
    path('list',consulatlist,name='consulat_list'),  
    path('list/<int:id>',consulatdetail,name='detail'),
    path('add',add_counslating,name='add_counslating'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path("admin/", admin.site.urls),
    path('', include('home.urls',namespace = 'home')),
    path('consulat/', include('consulat.urls',namespace = 'consulat'),),
    path('about/', include('about.urls',namespace = 'about')),
    path('blog/', include('blog.urls',namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/consulat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Counslat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    publish_date = models.DateField(default=timezone.now)
    description = models.TextField(max_length =1000)
    catgoray = models.ForeignKey('Catgory', on_delete=models.SET_NULL , null = True, blank = True)

    def __str__(self):
        return self.name





class Catgory(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500)
    created_at = models.DateField(default=timezone.now)
    counslat = models.ForeignKey(Counslat, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.user)

core/consulat/views.py
from django.shortcuts import render , redirect

from django.views.generic import ListView , DetailView
from .models import Counslat ,Comment
from .filters import FliterCounslat
from .froms import Reviews , Counslating
from accounts.models import Profile
from django.urls import reverse
from django.core.paginator import Paginator
# Create your views here.
#view all coulisting from database and take the queryset to django fliters to fliter resulat
def consulatlist(request):
    object_list = Counslat.objects.all()
    fliter = FliterCounslat(request.GET,Counslat.objects.all())
    paginator = Paginator(object_list, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'object_list':page_obj,'myfilter':fliter}
    return render(request,'consulat/counslat_list.html',context)

# view one comsulat by id and add comments 
def consulatdetail(request,id):
    consulat = Counslat.objects.get(id=id)
    review = Comment.objects.filter(counslat=consulat)
    user_info = Profile.objects.get(user=consulat.user)
    form = Reviews()
    if request.method == 'POST':
        form = Reviews(request.POST)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.counslat = consulat
            my_form.user = request.user
            my_form.save()
    context = {'consulat':consulat,'review':review,'form':form,'info':user_info}
    return render(request,'consulat/detail.html',context)


# add counslat to database
def add_counslating(request):
    form = Counslating()
    if request.method == 'POST':
        form = Counslating(request.POST)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.user = request.user
            my_form.save()
            return redirect(reverse('consulat:consulat_list'))
    return render(request,'consulat/add_counslat.html',{'form':form})

core/consulat/templates/consulat/add_counslat.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block 'body' %}
{% load static %}

<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
  </div>
    <!-- Quote Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title position-relative pb-3 mb-5">
                        <h5 class="fw-bold text-primary text-uppercase">Request A Quote</h5>
                        <h1 class="mb-0">Need A Free Quote? Please Feel Free to Contact Us</h1>
                    </div>
                    <div class="row gx-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
                            <h5 class="mb-4"><i class="fa fa-reply text-primary me-3"></i>Reply within 24 hours</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.4s">
                            <h5 class="mb-4"><i class="fa fa-phone-alt text-primary me-3"></i>24 hrs telephone support</h5>
                        </div>
                    </div>
                    <p class="mb-4">Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo rebum sea invidunt voluptua. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo invidunt lorem. Elitr ut dolores magna sit. Sea dolore sanctus sed et. Takimata takimata sanctus sed.</p>
                    <div class="d-flex align-items-center mt-2 wow zoomIn" data-wow-delay="0.6s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Call to ask any question</h5>
                            <h4 class="text-primary mb-0">+012 345 6789</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="bg-primary rounded h-100 d-flex align-items-center p-5 wow zoomIn" data-wow-delay="0.9s">
                        <form method = "post">
                            {% csrf_token %}
                            <div class="row g-3">
                                {% bootstrap_form form %}
                                {% buttons %}
                                <div class="col-12">
                                    <button class="btn btn-dark w-100 py-3" type="submit">Request A Quote</button>
                                {% endbuttons %}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Quote End -->

{% endblock 'body' %}

core/consulat/templates/consulat/counslat_list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block 'body' %}

<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
  </div>
    <!-- Blog Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <!-- Blog list Start -->
                <div class="col-lg-8">
                    <div class="row g-5">
                        {% for obj in object_list%}
                        <div class="col-md-6 wow slideInUp" data-wow-delay="0.1s" height="50%" width="50%" >
                            <div class="blog-item bg-light rounded overflow-hidden">
                                <div class="blog-img position-relative overflow-hidden">
                                    <img alt="" border="0" height="100%" width="100%" src="https://tinypic.host/images/2023/02/21/pikrepo.com-2.jpg"/> 
                                </div>
                                <div class="p-4">
                                    <div class="d-flex mb-3">
                                        <small class="me-3"><i class="far fa-user text-primary me-2"></i>{{obj.user.username}}</small>
                                        <small><i class="far fa-calendar-alt text-primary me-2"></i>{{obj.publish_date}}</small>
                                        <small><i class="fa-regular fa-pen-nib text-primary me-2"></i>{{obj.catgoray}}</small>
                                    </div>
                                    <h4 class="mb-3">{{obj.name}}</h4>
                                    <p>{{obj.description}}</p>
                                    <a class="text-uppercase" href="{% url 'consulat:detail' obj.id %}">More<i class="bi bi-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- Blog list End -->
    
                <!-- Sidebar Start -->
                <div class="col-lg-4">
    
                    <!-- Category Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Categories</h3>
                        </div>
                        <div class="link-animated d-flex flex-column justify-content-start">
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">
                            </form>
                        </div>
                    </div>
                    <!-- Category End -->
    

                    <!-- Plain Text Start -->
                    <div class="wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Plain Text</h3>
                        </div>
                        <div class="bg-light text-center" style="padding: 30px;">
                            <p>We pride ourselves on our personalized approach, tailoring our solutions to meet the unique needs of each client we work with. Our commitment to excellence, dedication to our clients' success, and extensive knowledge and expertise make us the go-to choice for consulting services. Let us help you unlock your full potential and achieve success.</p>
                        </div>
                    </div>
                    <!-- Plain Text End -->
                </div>
                <!-- Sidebar End -->
            </div>
        </div>
        {% if jobs.has_other_pages %}   
        <div class="row">
            <div class="col-lg-12">
                <div class="pagination_wrap">
                    <ul>
                        
                        {% if jobs.has_previous %}
                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                        {% endif %}

                        {% for i in jobs.paginator.page_range %}
                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                        {% endfor %}
                        


                        {% if jobs.has_next %}
                            <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    {% endif %} 
    </div>
    <!-- Blog End -->

{% endblock %}

core/consulat/templates/consulat/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block 'body' %}

<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>

                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
  </div>
       <!-- Blog Start -->
       <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-8">
                    <!-- Blog Detail Start -->
                    <div class="mb-5">
                        <img class="img-fluid w-100 rounded mb-5" src="{{info.image.url}}" alt="">
                        <h1 class="mb-4">user</h1>
                        <p>user: {{info}}</p>
                        <p>email: {{info.email}}</p>
                        <p>phone_number: {{info.phone}}</p>
                        <p>address: {{info.address}}</p>
                        <p>city: {{info.city}}</p>
                        <p>state: {{info.state}}</p>
                        <h1 class="mb-4">consulat</h1>
                        <p>consulat title: {{consulat.name}}</p>
                        <p>publish_date: {{consulat.publish_date}}</p>
                        <p>description: {{consulat.description}}</p>
                        <p>catgoray: {{consulat.catgoray}}</p>
                    </div>
                    <!-- Blog Detail End -->
    
                    <!-- Comment List Start -->
                    <div class="mb-5">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Comments</h3>
                        </div>
                        {% for obj in review %}
                        <div class="d-flex ms-5 mb-4">
                            <img src="img/user.jpg" class="img-fluid rounded" style="width: 45px; height: 45px;">
                            <div class="ps-3">
                                <h6><a href="">{{obj.user}}</a> <small><i>{{obj.created_at}}</i></small></h6>
                                <p>{{obj.comment}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Comment List End -->
                    {% if request.user.is_superuser %}
                    <!-- Comment Form Start -->
                    <div class="bg-light rounded p-5">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Leave A Comment</h3>
                        </div>
                        <form method = "post">
                            <div class="row g-3">
                                {% csrf_token %}
                                <div class="col-12 col-sm-6">
                                    {% bootstrap_form form %}
                                    {% buttons %}
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary w-100 py-3" type="submit">Leave Your Comment</button>
                                    {% endbuttons %}
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- Comment Form End -->
                    {% endif %}

                </div>
    
            </div>
        </div>
    </div>
    <!-- Blog End --> 
{% endblock 'body' %}