core/accounts/urls.py
from django.urls import path
from .views import profile , profile_edit , signup 

app_name = 'accounts'

urlpatterns = [
    path('signup',signup , name='signup'),
    path('profile/',profile,name='profile'),
    path('profile/edit', profile_edit , name='profile_edit') ,
]

core/blog/urls.py
from django.urls import path
from .views import blog_list , blog_detil
app_name = 'blog'
urlpatterns = [
    path('',blog_list,name='blog'),
    path('\<int:id>',blog_detil,name='detail'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path("admin/", admin.site.urls),
    path('', include('home.urls',namespace = 'home')),
    path('consulat/', include('consulat.urls',namespace = 'consulat'),),
    path('about/', include('about.urls',namespace = 'about')),
    path('blog/', include('blog.urls',namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@receiver(post_save, sender=User)
def createprofile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

core/accounts/forms.py
from django import forms
from . models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
# form for sgin up
class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

# edit form for Django User info
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']

# Edit the form for profile model 
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','name','email','phone','address','city','state']

core/accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Profile
from .forms import UserForm , ProfileForm , UserCreateForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib import messages


#View for user sgin up to check the user information
def signup(request):
    if request.method == 'POST':
        signup_form = UserCreateForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            # return redirect(reverse('login'))
            username = signup_form.cleaned_data['username']
            password = signup_form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('accounts:profile'))
    
    else:
        signup_form = UserCreateForm()

    return render(request,'registration/signup.html',{'signup_form':signup_form})


#Get the user profile for user who log in on page
def profile(request):
    profile = Profile.objects.get(user = request.user)
    return render(request,'profile/profile.html',{'profile':profile})


#Edit the proflie and user information
def profile_edit(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST , request.FILES , instance=profile)
        if profile_form.is_valid():
            my_form = profile_form.save(commit=False)
            my_form.user = request.user
            my_form.save()
            messages.success(request, 'Profile details updated.')
            return redirect(reverse('accounts:profile'))
    else:
        profile_form = ProfileForm(instance = profile)       

    return render(request,'profile/profile_edit.html',{'profile_form' : profile_form})

core/accounts/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}

<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0;
            background: rgba(9, 30, 62, .7);
            z-index: 1;">
                <div class="p-3" style="max-width: 900px;">
                    <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                    <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
  </div>

<section class="vh-100" style="background-color: #f4f5f7;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-6 mb-4 mb-lg-0">
          <div class="card mb-3" style="border-radius: .5rem;">
            <div class="row g-0">
              <div class="col-md-4 gradient-custom text-center text-white"
                style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;.gradient-custom {
                    /* fallback for old browsers */
                    background: #f6d365;
                    
                    /* Chrome 10-25, Safari 5.1-6 */
                    background: -webkit-linear-gradient(to right bottom, rgba(246, 211, 101, 1), rgba(253, 160, 133, 1));
                    
                    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                    background: linear-gradient(to right bottom, rgba(246, 211, 101, 1), rgba(253, 160, 133, 1))
                    }">
                {% if profile.image %}
                <img src="{{profile.image.url}}"alt="Avatar" class="img-fluid my-5" style="width: 100px;" />
                {% else %}
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
                {% endif %}
                <h5>{{profile}}</h5>
                <i class="far fa-edit mb-5"></i>
              </div>
              <div class="col-md-8">
                <div class="card-body p-4">
                  <h6>Information</h6>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>Email</h6>
                      <p class="text-muted">{{profile.user.email}}</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>Phone</h6>
                      <p class="text-muted">{{profile.phone}}</p>
                    </div>
                  </div>
                  <h6>more info</h6>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>address</h6>
                      <p class="text-muted">{{profile.address}}</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>state</h6>
                      <p class="text-muted">{{profile.state}}</p>
                    </div>
                  </div>
                  <div class="d-flex justify-content-start">
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <a href="{% url 'accounts:profile_edit' %}" type="button" class="btn btn-primary py-md-2 px-md-5 me-2 animated slideInLeft">edit proflie</a>
                      <a  href="{% url 'logout' %}"  type="button" class="btn btn-outline-dark py-md-2 px-md-4 animated slideInRight">log out</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

core/accounts/templates/profile/profile_edit.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block 'body' %}
    


<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
      <div class="carousel-item active">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
              </div>
          </div>
      </div>
      <div class="carousel-item">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
              </div>
          </div>
      </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
</div>




<div class="row">
    <div class="col-md-4 mx-auto mt-5 mb-5">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form profile_form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary py-3">Edit Profile</button>
            {% endbuttons %}
        
        </form>
    </div>
</div>


 {% endblock %}