core/about/urls.py
from django.urls import path
from .views import about 
app_name = 'about'
urlpatterns = [
    path('about',about,name='about')
]

core/accounts/urls.py
from django.urls import path
from .views import profile , profile_edit , signup 

app_name = 'accounts'

urlpatterns = [
    path('signup',signup , name='signup'),
    path('profile/',profile,name='profile'),
    path('profile/edit', profile_edit , name='profile_edit') ,
]

core/blog/urls.py
from django.urls import path
from .views import blog_list , blog_detil
app_name = 'blog'
urlpatterns = [
    path('',blog_list,name='blog'),
    path('\<int:id>',blog_detil,name='detail'),
]

core/consulat/urls.py
from django.urls import path
from .views import consulatlist , consulatdetail , add_counslating
app_name = 'consulat'
urlpatterns = [
    path('list',consulatlist,name='consulat_list'),  
    path('list/<int:id>',consulatdetail,name='detail'),
    path('add',add_counslating,name='add_counslating'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path("admin/", admin.site.urls),
    path('', include('home.urls',namespace = 'home')),
    path('consulat/', include('consulat.urls',namespace = 'consulat'),),
    path('about/', include('about.urls',namespace = 'about')),
    path('blog/', include('blog.urls',namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Consulting Website</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner"></div>
    </div>
    <!-- Spinner End -->




    <!-- Navbar & Carousel Start -->
    <div class="container-fluid position-relative p-0" >
        <nav class="navbar navbar-expand-lg navbar-dark px-5 py-3 py-lg-0" style=" position: absolute;
        width: 100%;
        top: 0;
        left: 0;
        border-bottom: 1px solid rgba(256, 256, 256, .1);
        z-index: 999;">
            <a href="/" class="navbar-brand p-0">
                <h1 class="m-0" style="color: aliceblue;"><i class="fa fa-user-tie me-2" style="color: aliceblue;"></i>consulating</h1>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto py-0">
                    <a href="/" class="nav-item nav-link">Home</a>
                    <a href="{% url 'about:about' %}" class="nav-item nav-link">About</a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'consulat:consulat_list' %}" class="nav-item nav-link ">consulat</a>
                    {% endif %}
                    <a href="{% url 'blog:blog' %}" class="nav-item nav-link ">blog</a>
                </div>
                {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:profile' %}" class="btn btn-primary py-2 px-4 ms-3">proflie</a>
                <a href="{% url 'consulat:add_counslating' %}" class="btn btn-primary py-2 px-4 ms-3"> add consulat</a>
                {% else %}
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary py-2 px-4 ms-3">sginup</a>
                <a href="{% url 'login' %}" class="btn btn-primary py-2 px-4 ms-3">login</a>
                {% endif %}
                
            </div>
        </nav>
    </div>


    <!-- Navbar & Carousel End -->
<!-- Full Screen Search Start -->
<div class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">

        <div class="modal-content" style="background-color: rgba(9, 30, 62, .7);">
            <div class="modal-header border-0">
                <button type="button" class="btn bg-white btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                <div class="input-group" style="max-width: 600px;">
                    <input type="text" class="form-control bg-transparent border-primary p-3" placeholder="Type search keyword">
                    <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Full Screen Search End -->

   {% block 'body' %}
    
   {% endblock 'body' %}  


   <div class="container-fluid bg-dark px-5 d-none d-lg-block">
    <div class="row gx-0">
        <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
            <div class="d-inline-flex align-items-center" style="height: 45px;">
                <small class="me-3 text-light"><i class="fa fa-map-marker-alt me-2"></i>123 Street, Saudi Arabia, KSA</small>
                <small class="me-3 text-light"><i class="fa fa-phone-alt me-2"></i>+053 389 333777</small>
                <small class="text-light"><i class="fa fa-envelope-open me-2"></i>consulating@hotmail.com</small>
            </div>
        </div>
        <div class="col-lg-4 text-center text-lg-end">
            <div class="d-inline-flex align-items-center" style="height: 45px;">
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-twitter fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-facebook-f fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-linkedin-in fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href=""><i class="fab fa-instagram fw-normal"></i></a>
                <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href=""><i class="fab fa-youtube fw-normal"></i></a>
            </div>
        </div>
    </div>
</div>
    <!-- Footer End -->

    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>