core/blog/urls.py
from django.urls import path
from .views import blog_list , blog_detil
app_name = 'blog'
urlpatterns = [
    path('',blog_list,name='blog'),
    path('\<int:id>',blog_detil,name='detail'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path("admin/", admin.site.urls),
    path('', include('home.urls',namespace = 'home')),
    path('consulat/', include('consulat.urls',namespace = 'consulat'),),
    path('about/', include('about.urls',namespace = 'about')),
    path('blog/', include('blog.urls',namespace='blog')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from consulat.models import Catgory
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_post')
    title = models.CharField(max_length=100)
    content = models.TextField()
    catgory = models.ForeignKey(Catgory, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

core/blog/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

#Get all the posts from database
def blog_list(request):
    obj = Post.objects.all()
    return render(request, 'blog/post_list.html',{'obj':obj})

#Get single post by id
def blog_detil(request,id):
    obj = Post.objects.get(id=id)
    return render(request, 'blog/post_detail.html',{'obj':obj})

core/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
    


<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
      <div class="carousel-item active">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
              </div>
          </div>
      </div>
      <div class="carousel-item">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>
              </div>
          </div>
      </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-8">
                <!-- Blog Detail Start -->
                <div class="mb-5">
                    <img class="img-fluid w-100 rounded mb-5" src="img/blog-1.jpg" alt="">
                    <h1 class="mb-4">{{obj}}</h1>
                   
                    <p>{{obj.content}}</p>
                </div>
                <!-- Blog Detail End -->
            </div>

            </div>
            <!-- Sidebar End -->
        </div>
    </div>
</div>
{% endblock 'body' %}

core/blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
    


<div id="header-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
      <div class="carousel-item active">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>

              </div>
          </div>
      </div>
      <div class="carousel-item">
          <img class="w-100" src="{% static 'img/carousel-2.jpg' %}" alt="Image">
          <div class="carousel-caption d-flex flex-column align-items-center justify-content-center" style=" top: 0px;
          left: 0px;
          right: 0px;
          bottom: 0;
          background: rgba(9, 30, 62, .7);
          z-index: 1;">
              <div class="p-3" style="max-width: 900px;">
                  <h5 class="text-white text-uppercase mb-3 animated slideInDown">Creative & Innovative</h5>
                  <h1 class="display-1 text-white mb-md-4 animated zoomIn">Creative & Innovative Digital Solution</h1>

              </div>
          </div>
      </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
  </button>
</div>


<div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
  <div class="container py-5">
      <div class="row g-5">
          <!-- Blog list Start -->
          <div class="col-lg-8">
              <div class="row g-5">
                {% for obj in obj %}
                <div class="col-md-6 wow slideInUp" data-wow-delay="0.1s" height="50%" width="50%" >
                    <div class="card">
                        <img src="https://images.unsplash.com/photo-1477862096227-3a1bb3b08330?ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" alt="" class="card-img-top">
                        <div class="card-body">
                          <h5 class="card-title">{{obj}}</h5>
                          <p class="card-text">{{obj.content|safe}}</p>
                         <a href="{% url 'blog:detail' obj.id %}" class="btn btn-outline-danger btn-sm">Read More</a>
                        </div>
                       </div>
                      </div>
                </div>
                {% endfor %}


              </div>
          </div>
          <!-- Blog list End -->
      </div>
  </div>
</div>

{% endblock 'body' %}